version: "3.9"
services:
    next:
        container_name: ${NEXT_CONTAINER_NAME}
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
            args:
                NEXT_NODE_VERSION: ${NEXT_NODE_VERSION}
                NEXT_LOCAL_PATH: ${PWD}/${NEXT_LOCAL_PATH}
                NEXT_WORKDIR: ${NEXT_WORKDIR}
        volumes:
            - ./${NEXT_LOCAL_PATH}:${NEXT_WORKDIR}
        ports:
            - ${NEXT_LOCAL_PORT}:${NEXT_PORT}
        tty: true
    api:
        container_name: ${API_CONTAINER_NAME}
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
            args:
                GO_VERSION: ${GO_VERSION}
                API_CODE_WORKDIR: ${API_CODE_WORKDIR}
        environment:
            - POSTGRESQL_URL=${POSTGRESQL_URL}
        volumes:
            - ./${API_CODE_LOCAL_PATH}:${API_CODE_WORKDIR}
        ports:
            - ${API_LOCAL_PORT}:${API_PORT}
        tty: true
    postgres:
        container_name: ${POSTGRES_CONTAINER_NAME}
        image: postgres:${POSTGRES_TAG}
        ports:
            - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGPASSWORD=${POSTGRES_PGPASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_NAME}
            - TZ=${POSTGRES_TIMEZONE}
        tty: true
        restart: always
        user: root
        volumes:
            - ${POSTGRES_LOCAL_PATH}:/var/lib/postgresql/data