// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	UserRoles string
	Users     string
}{
	UserRoles: "user_roles",
	Users:     "users",
}
