// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ColaResults   string
	ColaTypes     string
	Manufacturers string
	Packages      string
	UserRoles     string
	Users         string
}{
	ColaResults:   "cola_results",
	ColaTypes:     "cola_types",
	Manufacturers: "manufacturers",
	Packages:      "packages",
	UserRoles:     "user_roles",
	Users:         "users",
}
