// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testColaTypes(t *testing.T) {
	t.Parallel()

	query := ColaTypes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testColaTypesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testColaTypesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ColaTypes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testColaTypesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ColaTypeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testColaTypesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ColaTypeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ColaType exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ColaTypeExists to return true, but got false.")
	}
}

func testColaTypesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	colaTypeFound, err := FindColaType(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if colaTypeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testColaTypesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ColaTypes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testColaTypesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ColaTypes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testColaTypesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	colaTypeOne := &ColaType{}
	colaTypeTwo := &ColaType{}
	if err = randomize.Struct(seed, colaTypeOne, colaTypeDBTypes, false, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}
	if err = randomize.Struct(seed, colaTypeTwo, colaTypeDBTypes, false, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = colaTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = colaTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ColaTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testColaTypesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	colaTypeOne := &ColaType{}
	colaTypeTwo := &ColaType{}
	if err = randomize.Struct(seed, colaTypeOne, colaTypeDBTypes, false, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}
	if err = randomize.Struct(seed, colaTypeTwo, colaTypeDBTypes, false, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = colaTypeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = colaTypeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func colaTypeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func colaTypeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ColaType) error {
	*o = ColaType{}
	return nil
}

func testColaTypesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ColaType{}
	o := &ColaType{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, colaTypeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ColaType object: %s", err)
	}

	AddColaTypeHook(boil.BeforeInsertHook, colaTypeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	colaTypeBeforeInsertHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.AfterInsertHook, colaTypeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	colaTypeAfterInsertHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.AfterSelectHook, colaTypeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	colaTypeAfterSelectHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.BeforeUpdateHook, colaTypeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	colaTypeBeforeUpdateHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.AfterUpdateHook, colaTypeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	colaTypeAfterUpdateHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.BeforeDeleteHook, colaTypeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	colaTypeBeforeDeleteHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.AfterDeleteHook, colaTypeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	colaTypeAfterDeleteHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.BeforeUpsertHook, colaTypeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	colaTypeBeforeUpsertHooks = []ColaTypeHook{}

	AddColaTypeHook(boil.AfterUpsertHook, colaTypeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	colaTypeAfterUpsertHooks = []ColaTypeHook{}
}

func testColaTypesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testColaTypesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(colaTypeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testColaTypesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testColaTypesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ColaTypeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testColaTypesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ColaTypes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	colaTypeDBTypes = map[string]string{`ID`: `integer`, `ManufacturerID`: `integer`, `Name`: `character varying`, `Amount`: `integer`, `PackageID`: `integer`, `Calories`: `integer`}
	_               = bytes.MinRead
)

func testColaTypesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(colaTypePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(colaTypeAllColumns) == len(colaTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testColaTypesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(colaTypeAllColumns) == len(colaTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ColaType{}
	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, colaTypeDBTypes, true, colaTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(colaTypeAllColumns, colaTypePrimaryKeyColumns) {
		fields = colaTypeAllColumns
	} else {
		fields = strmangle.SetComplement(
			colaTypeAllColumns,
			colaTypePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ColaTypeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testColaTypesUpsert(t *testing.T) {
	t.Parallel()

	if len(colaTypeAllColumns) == len(colaTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ColaType{}
	if err = randomize.Struct(seed, &o, colaTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ColaType: %s", err)
	}

	count, err := ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, colaTypeDBTypes, false, colaTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ColaType struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ColaType: %s", err)
	}

	count, err = ColaTypes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
