// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ColaResults", testColaResultsUpsert)

	t.Run("ColaTypes", testColaTypesUpsert)

	t.Run("Manufacturers", testManufacturersUpsert)

	t.Run("Packages", testPackagesUpsert)

	t.Run("UserRoles", testUserRolesUpsert)

	t.Run("Users", testUsersUpsert)
}
